# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Coverage configuration
# ----------------------
coverage:
  status:
    project:
      default:
        threshold: 5
        if_not_found: success
    patch:
      default: off
    changes:
      default: off