---
PORT: 8085
CLUSTER: localhost
PbDbType: inmemory
PulsarPublicKey: ./unit-test/example_public_key.pub
PulsarPrivateKey: ./unit-test/example_private_key
PbDbInterval: 10s
DbConnectionStr: mongodb://localhost:27017
DbName: 
DbPassword:
TrustStore: "/etc/ssl/certs/ca-bundle.crt"